### PR TITLE
Bad formatting in README

### PR DESCRIPTION
**Pull request by Luni-4**

### CODE REVIEW

**Comment by rr-** [comment]
What's the point of this change?

**Comment by Luni-4** [comment]
> What's the point of this change?

Remove a useless blank line and group `<br />` together

**Comment by rr-** [comment]
No thanks

**Comment by Luni-4** [comment]
> No thanks

Could you elaborate your choice, please?

**Comment by rr-** [comment]
I simply don't like how it replaces a blank lines with a space.
Also it's better to put our energy someplace else.

**Comment by Luni-4** [comment]
> I simply don't like how it replaces a blank line with a space.
> Also it's better to put our energy someplace else.

I removed a blank line. There were two lines, now there is only one, as all in the other parts of the README. If you don't link how I grouped <br /> together, I can leave them untouched.

**Comment by rr-** [comment]
That change is unnecessary as well.

**Comment by Luni-4** [comment]
> That change is unnecessary as well.

I can't understand, but if you like my error of making the README incoherent, it's ok for me.

**Comment by rr-** [comment]
First, it's just formatting of a Markdown file that contains HTML.
Second, a double blank line under an elaborate header to separate it from the rest of the content is ok.

**Comment by Luni-4** [comment]
> First, it's just formatting of a Markdown file that contains HTML.
> Second, a double blank line under an elaborate header to separate it from the rest of the content is ok.

Fine, let's keep this PR closed then.

**Pull request closed without merging**
