### PR TITLE
Add a command to unselect the spectrogram to the menu

### PR DESCRIPTION
**Pull request by Luni-4**

### CODE REVIEW

**Comment by rr-** [comment]
What's the motivation for this command? What do you use it for?

**Comment by Luni-4** [comment]
> What's the motivation for this command? What do you use it for?

I would have used this command to unselect the entire spectrogram, but adding a new sub the selection disappears. So we can close this PR

**Comment by rr-** [comment]
>I would have used this command to unselect the entire spectrogram

This is my question - why? What for?

**Comment by Luni-4** [comment]
> > I would have used this command to unselect the entire spectrogram
> 
> This is my question - why? What for?

Because I found more comfortable clicking a button instead of modifying the spectrogram through the mouse, but that's just my preference, it doesn't apply to anyone. That's why I closed this PR.

**Pull request closed without merging**
