### PR TITLE
Refactor menu entries

### PR DESCRIPTION
**Pull request by Luni-4**

### CODE REVIEW

**Comment by rr-** [comment]
1. I'd rename `create audio sample` to `save audio sample` and put it at the bottom of the `audio` submenu (for consistency with screenshot commands)
2. Please remove the line between "play until end of file" and "play around spectrogram selection", there's too many lines in that submenu
3. Please change `Subtitles` menu accelerator to something else as <kbd>Alt+S</kbd> is used to focus the subtitles grid
4. Please change `Audio` menu accelerator to something else as <kbd>Alt+A</kbd> is used to focus the spectrogram
5. Please add an accelerator that doesn't conflict with anything to the Video submenu
6. Please move split commands under the `Subtitle` menu into a submenu near the `Merge subtitles` submenu for the sake of consistency
7. Please consider moving `Pause` and `Toggle pause` commands to the `Playback` menu as it affects both audio and video
8. Please consider renaming the `Subtitle` menu to `Subtitles`
9. Please consider the following order: `File` → `View` → `Edit` → `Subtitle` → `Video` → `Audio` → `Playback` → `Timing` → `Plugins`
10. Please move jump commands section in the `Subtitles` menu higher, under the `Styles manager` command
11. Please consider moving selection commands to the `Edit` submenu (motivation: search and replace affects only subtitles, too, so might as well have standard selection commands there as well)

**Comment by Luni-4** [comment]
Done!

>2. Please remove the line between "play until end of file" and "play around spectrogram selection" (there's too many lines in that submenu)

I have moved "Play Spectogram Selection" just above "Play around spectrogram selection" without removing the line below "Toggle pause". I think it's more clear this way.

**Comment by rr-** [comment]
Almost ready to merge, just a couple of minor things:

- Please remove accelerators in submenus. Qt by default lets you navigate by items' first letters in opened menus, so it doesn't make much sense to provide them. (I'm responsible for this mess)
- Please move "play selected subtitle" above "Play spectrogram selection".
- Please add a menu item to reset the playback speed to 100% (to stay consistent with the audio volume menu).
- `Vide&o` is rather poor, how about `V&ideo`?
- Can you think of any sound replacement for the widget focus hotkeys that doesn't conflict with accelerators?

**Comment by Luni-4** [comment]
>     * `Vide&o` is rather poor, how about `V&ideo`? (Does it conflict with anything?)

I really don't like it visually, but `V&ideo` doesn't conflict with anything.

>     * Can you think of any sound replacement for the widget focus hotkeys that doesn't conflict with accelerators?

I will do this one in another PR. Let's merge this way for now.

**Comment by rr-** [comment]
Merged, thanks. I'll remove the accelerators while I'm at it.

**Pull request merged**
