### PR TITLE
Disable useless commands at startup

### PR DESCRIPTION
**Pull request by Luni-4**
I guess it's better to disable commands that can't be used by the user when there are no media or subs.

### CODE REVIEW

**Comment by rr-** [comment]
I don't know about spectrogram commands. I was planning on making the spectrogram usable even without any media file.

**Comment by Luni-4** [comment]
> I don't know about spectrogram commands. I was planning on making the spectrogram usable even without any media file.

Sorry, but I can't get the point here, shame on me. I mean, how do you make the spectogram usable without any media file?

> Also, I had a reason for making `all` and `none` available at all times, which I of course don't remember now. In the logical sense, doing something to all subs if there are no subs shouldn't throw an exception, but rather be a no-op operation. Even more so for no subs.

Yeah, no exception is thrown, but I guess it's more logical to prevent the user from making useless op rather than let him do them. Again, this is just my point of view, I can remove them if you don't like this kind of approach.
 
> Playback speed and volume – again, no. You don't need to load anything to be able to fiddle with these properties. They're supposed to work across media loads.

Same reason as above

**Comment by rr-** [comment]
>Sorry, but I can't get the point here, shame on me. I mean, how do you make the spectogram usable without any media file?

It can still render the rectangles with where subtitles start and end, which is useful visualization IMO even if it doesn't show the audio samples data.

**Comment by Luni-4** [comment]
> > Sorry, but I can't get the point here, shame on me. I mean, how do you make the spectogram usable without any media file?
> 
> It can still render the rectangles with where subtitles start and end, which is useful visualization IMO even if it doesn't show the audio samples data. I'd go in that direction.

I opened a video without any audio data. Rectangles were rendered perfectly and commands were enabled correctly as well.

But, if I try to zoom in/out, snap, or shift spectogram without any video loaded, I get lots of exceptions. That's why I've disabled spectogram commands at startup.

**Comment by rr-** [comment]
>I opened a video without any audio data. Rectangles were rendered perfectly and commands were enabled correctly as well.

Yes. Now if you open subtitles without any media file, it doesn't work.

**Pull request closed without merging**
